# Generated by Django 3.1.3 on 2020-11-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('suggestions', models.JSONField()),
                ('threshold_steps', models.IntegerField()),
                ('threshold_strength', models.FloatField()),
            ],
        ),
    ]
