# Generated by Django 3.1.3 on 2020-11-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201107_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
