name: Publish Backend

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: google/cloud-sdk
    steps:
    - uses: actions/checkout@master
    - name: Build docker image
      run: |
        docker build -t eu.gcr.io/health-hack-guardian/guardian-backend:${{ github.event.release.tag_name }} ./backend
