name: Publish Backend

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend/guardian
    steps:
    - uses: actions/checkout@master
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Setup gcloud environment
      # You may pin to the exact commit or the version.
      # uses: google-github-actions/setup-gcloud@61938f87149d8a75fd3d7385a5081d8a4169156d
      uses: google-github-actions/setup-gcloud@0.1.2
      with:
        # The service account email which will be used for authentication.
        service_account_email: backend-ci@health-hack-guardian.iam.gserviceaccount.com
        # The service account key which will be used for authentication.
        service_account_key: ${{ secrets.BACKEND_CI_KEY }}

    - name: Build Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@6efc2b01cbb63cfc68c370c6c806586fa6384a3a
      uses: docker/build-push-action@v2
      with:
        context: ./backend/
        file: ./backend/Dockerfile
        tags:  eu.gcr.io/health-hack-guardian/guardian-backend:${{ github.event.release.tag_name }}
        load: true

    - name: Configure Docker login
      run: |
        gcloud auth configure-docker
        docker push eu.gcr.io/health-hack-guardian/guardian-backend:${{ github.event.release.tag_name }}
        gcloud run deploy "guardian-backend" --project health-hack-guardian \
          --region "europe-west6" \
          --image "eu.gcr.io/health-hack-guardian/guardian-backend:${{ github.event.release.tag_name }}" \
          --platform "managed" \
          --allow-unauthenticated
