
name: Publish Frontend

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend/guardian 
    steps:
    - uses: actions/checkout@master
    - name: Set up Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '14.15.0'
    - name: npm install and npm run build
      run: |
        npm install
        npm run build-prod
      working-directory: ${{env.working-directory}}
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: ./frontend/guardian/dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: ./frontend/guardian/dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          PROJECT_PATH : ./frontend/guardian
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID:  health-hack-guardian
